spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 3
    # Redis服务器地址
    host: 120.48.127.223
    # Redis服务器连接端口
    port: 6379
    # Redis服务器链接密码（默认为空）
    password: 3C&wjx@666!
    jedis:
      pool:
        # 连接池最大链接数（负值表示没有限制）
        max-active: 20
        # 连接池最大阻塞等待时间（负值表示没有限制）
        max-wait: -1
        # 链接池中最大空闲链接
        max-idle: 10
        # 连接池中最小空闲链接
        min-idle: 0
    # 链接超市时间（毫秒）
    timeout: 1000