server:
  port: 8088
spring:
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 120.48.127.223:8848
        username: nacos
        password: nacos
  application:
    name: grpc_client
grpc:
  client:
    grpc_server:
      negotiation-type: plaintext